// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package output

import mock "github.com/stretchr/testify/mock"

// MockProgress is an autogenerated mock type for the Progress type
type MockProgress struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MockProgress) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *MockProgress) Stop() {
	_m.Called()
}

// Tic provides a mock function with given fields:
func (_m *MockProgress) Tic() {
	_m.Called()
}
